### ISSUE TITLE
Apply for Grants

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#101]
Apply for Grants to help fund the DaBible Missionary fund and other DaBible Activites

**Comment by sanmiayotunde** [comment]
@olasubomi-o can you please specify or link to a doc about all the grants we have applied for?

**Comment by olasubomi-o** [comment]
[Google docs on the grant we applied to](https://docs.google.com/document/d/1W3lryKhk_aSOhqEsqZtjEHBzePjkeVSyhnae4Y9Vcr8/edit?usp=sharing)

**Comment by olasubomi-o** [comment]
- [ ] Kingdom Mission Fund - Applied to

- [ ] Maclellan - Applied

- [ ] Amos Foundation - Applied 

- [ ] https://www.grantrequest.com/AccountManager.aspx?sid=5514 - Applied

- [ ] http://crowelltrust.org/apply-for-a-grant/ - Bro Sanmi apply

- [ ] NCF- Contacted

If you find any grants we can apply to be sure to comment on this issue.
