### ISSUE TITLE
How to use slack in DaBible - Foundation explanation.

### ISSUE THREAD

**Issue by benedictatommy** [DaBible-Foundation/DaBible-MainHub#105]
Hello, Please can someone explain more about slack and how to use.

**Comment by sanmiayotunde** [comment]
@olasubomi-o or @emmanlex please create a WIKI page on our handbook to explain how volunteers can join our slack channel, and a good tutorial about how to use slack.

- [ ] Explained how to join slack
- [ ] Explained how to use slack - preferably a video
- [ ] Emphasize communication in channel above direct messaging

**Comment by olasubomi-o** [comment]
@emmanlex I would make the video tutorial and you can make the wiki page?

**Comment by sanmiayotunde** [comment]
@olasubomi-o creating a WIKI is very simple too, its just like dropping a comment here

**Comment by sanmiayotunde** [comment]
This issue have been resolved.
