### ISSUE TITLE
 Feedback to client on the Amove project

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#106]
@sanmiayotunde is to provide feedback to the client on the status of the Amove project. For this project, we are going to create an android app so we need to hire a UI designer to make a wireframe. 

- [ ] Find a UI designer for the app
- [ ] Present finding to the client

**Comment by sanmiayotunde** [comment]
This project have been delivered, waiting for client to make the deposit required to start the amove project.
