### ISSUE TITLE
Install Franz all in one social media app locally and generate a build.

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#108]
In order to manage your various slack workspaces, WhatsApp accounts, and other communicating tools. I will be installing Franz locally, then generating an electron desktop app that I will be using to manage my social media accounts.

If you are interested, let me know. Details about Franz here https://github.com/meetfranz/franz

The free version of Franz allows only 3 accounts, but with the developer access to the code, we can build the app ourselves and use it as we like lol.

This will be awesome.

**Comment by sanmiayotunde** [comment]
I have started wrking on this issue

**Comment by emmanlex** [comment]
I am interested

**Comment by sanmiayotunde** [comment]
@emmanlex you can install franz and use the free trial and also use it after free trial. It's an amazing tool. I will close this issue right away.
