### ISSUE TITLE
Create a blast email campaign about Leviticus Makpa 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#109]
Create a blast email campaign that we sending to subscribers about the recent demise of Leviticus Makpa —the two blog posts we created. Our goal is to encourage support for the widow Benita Makpa.

**Comment by sanmiayotunde** [comment]
@emmanlex  This issue have been done, but can we check if all the emails were delivered?

**Comment by sanmiayotunde** [comment]
@emmanlex  I have checked our Mautic account, we need to resend the remaining in batches of 100s, and we ave to do it after waiting for some time.

**Comment by emmanlex** [comment]
This issue was completed an email was sent to everyone on our Mautic list. We had some issues sending the messages and now we know to send them in batches.
