### ISSUE TITLE
Refactor Blog for mobile devices 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#114]
The blogs on the mobile app appear buggy. The inline editor used in creating the blogs does not translate well over to mobile. This blog post needs to be refactored and we will no longer be using inline editor to create a blog post. 

- [x] Refactor blogs post on the website to ease mobile use 
- [x] Create a design template for blogs

**Additional information:**

**Comment by sanmiayotunde** [comment]
@olumese have helped us to clean out all these blog posts. We are are good to push LIVE
