### ISSUE TITLE
Review contents on DaBible.com

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#12]
Reviewing all the contents published on the DaBible.com. Checking each webpages and creating a standard for future editing.

Goal: to increase traffic on all webpages.
Process of determination: using SEO standard (Keyword phrase, optimization and authority) 
Result determination: google analytic timeline of before and after for the duration of 3 months after editing.

**Comment by sanmiayotunde** [comment]
We have resolved this issue. We need to close it.
