### ISSUE TITLE
Edit Anchor.fm Name Format

### ISSUE THREAD

**Issue by kehinde2134** [DaBible-Foundation/DaBible-MainHub#121]
Change naming convention for each of these bible books on anchor.fm. 

for example:

Yoruba Audio Bible - 1 SAMUEL - SAMUELI KINNI 4 -------> 1 SAMUEL 4 - SAMUELI KINNI 4 (Yoruba Bible)

Note: Never do revert to draft. 

- [x] 9. 1 Samuel
- [x] 10. 2 Samuel
- [x] 11. 1 Kings
- [x] 12. 2 Kings
- [x] 13. 1 Chronicles
- [x] 14. 2 Chronicles
- [x] 15. Ezra
- [x] 16. Nehemiah
- [x] 17. Esther
- [x] 18. Job
- [x] 19. Psalms
- [x] 20. Proverbs
- [x] 21. Ecclesiastes
- [x] 22. Song of Solomon

**Comment by emmanlex** [comment]
@fagb3mi @kehinde2134 worked on completing this issue and have started another issue which involves arranging the Saudi in the right order.
