### ISSUE TITLE
Link Audio on Anchor to Amazon music 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#131]
Please link the audio from anchor.fm to amazon music using RSS Feed.

**Comment by olasubomi-o** [comment]
Completed 
![Screen Shot 2021-05-29 at 10 47 22 AM](https://user-images.githubusercontent.com/67253470/120076529-9d6afc00-c06b-11eb-8468-bbb35a417184.png)
