### ISSUE TITLE
Rename files for the Hausa audio bible

### ISSUE THREAD

**Issue by fagb3mi** [DaBible-Foundation/DaBible-MainHub#137]
Rename the folder names and file names for Hausa audio bible that need to be renamed

**Comment by aluko123** [comment]
This is the text that you entered into the textbox!

**Comment by aluko123** [comment]
Added from Slack: [TEST/USER] hi

**Comment by aluko123** [comment]
Added from Slack: @oaa0008 here is what we need to do with GITHUB, we want all the messages to come into #dabible-foundation channel, not the general.

**Comment by aluko123** [comment]
Added from Slack: This may be interesting o, now lets see if we can push the message back to GitHub

**Comment by sanmiayotunde** [comment]
Issue is now resollved.
