### ISSUE TITLE
Welcome to DaBible Foundation Blog post MVC 2

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#14]
Improve the existing welcome to DaBible Foundation blog post for MVC 2.

Related: https://github.com/sanmiayotunde/DaBible-Foundation/issues/2

**Comment by sanmiayotunde** [comment]
This task is long due, we need to get this done asap, its from a very old milestone

**Comment by sanmiayotunde** [comment]
@emmanlex are we still going to do this task?

**Comment by emmanlex** [comment]
Yes sir, I will turn in what I have so far.

**Comment by emmanlex** [comment]
@sanmiayotunde

**Comment by sanmiayotunde** [comment]
Oh alright

**Comment by emmanlex** [comment]
SECOND MVC
Many thanks to our listeners and app users for your support. Be kindly informed that the site, Yorubabible.net is now down and would no longer be in use. Instead, please visit DaBible.com for full audio recordings and readings of the Yoruba bible. Dabible.com is owned and managed by DaBible Foundation. Our goal in DaBible Foundation is to provide clear and audible translations of the bible in various African languages. We are devoted to bringing you the word of God in the comfort of your homes, on your computers and your mobile devices. Our Mobile App has been built to be simple and easy to navigate. The DaBible Foundation right from its very conception has been led by God's divine direction and we put him foremost in all we do. We value the word of God and find it is important to have a full understanding of everything in the Bible. Truly, what better way to listen to God’s word than for it to be heard in a familiar language. New testimonies are coming your way as you use these apps.
All team members are volunteers, who work to provide the best experience we can offer on all our platforms. You can see how it all started on OUR STORY page.
Presently, we have two apps available for downloads. The Yoruba audio bible app you know, and love is still available on apple store and google play store to download. Our newly released pidgin audio bible app is also available on the apple and google play stores, Just click this link for more info (https://dabible.com/pidgin/). Released in 2020 our pidgin audio bible is our second production of the like. With both old and new testament translated to pidgin; the Pidgin bible is the very first of its kind. You can find both of our apps available on the apple store and google pay store for both IOS and android downloads for FREE. We have gone one step further in our mission of providing audio and text, transcribed and recorded in familiar African languages.
So, go on to your apple stores and google stores and get a copy of your very own Pidgin audio bible app. Our apps are developed by DaBible foundation to be easy to navigate and we even have features for offline downloads. So, wherever you are, as long as you have internet access you can download the files to your phone and then can listen to your Bible chapters and bible books whenever you want. Easy and convenient.
Similarly, the Yoruba audio bible app, created by DaBible foundation remains available for downloads on apple and android devices. We have been constantly making updates and we have our apps ready for offline mode. Just like with the Pidgin audio bible app, you can download the audio files onto your phone and can listen at your own convenience.
In other news, we are pleased to inform you that we are soon to release a Hausa audio bible too. Visit https://dabible.com/hausa/ for updates on our release dates to know the when and how you can access this amazing content. Another 
As you may already know, our contents including our audio Bible apps are all FREE. We are dedicated to our mission of getting the word of God across to people in their own tongue. Lastly, we are expressly grateful to our donors for their support, the almighty God will continue to bless the works of your hand.
On this note, let me be the first to welcome you to our new and ever improving DaBible.com.
