### ISSUE TITLE
Audio progress bar buggy on next chapter click

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#144]
- [ ] Audio progress bar buggy on next chapter click
- [ ] Play/pause button not working
- [ ] Audio from previous chapter doesn't stop when you turn to next chapter

_Originally posted by @aluko123 in https://github.com/DaBible-Foundation/DaBible-MainHub/issues/91#issuecomment-841388002_

**Comment by emmanlex** [comment]
This issue will be placed on a backlog
