### ISSUE TITLE
Request to Join DaBible Foundation Slack Channel

### ISSUE THREAD

**Issue by olumese** [DaBible-Foundation/DaBible-MainHub#149]
Hello Administrator,

I will love to join DaBible Foundation slack channel. 

## Your Information:

First and Last name: Ikhuoria Oselumese

Location: 
Redlands CA
Email*: olumeseikhuoria@gmail.com

Why I want to join DaBible Foundation: 

Thanks.

**Comment by sanmiayotunde** [comment]
Invitation to join slack sent. Thanks!
