### ISSUE TITLE
Setup Audio on Website 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#151]
Using Anchor.fm we can have the bible audio play on the DaBible website. @sanmiayotunde Please complete the process of setting this up. Thank you

**Comment by sanmiayotunde** [comment]
I am currently working on this issue right now/.

Thanks,
*Sanmi Ayotunde Ajanaku*
Team Leader - DaBible Foundation
www.dabible.com
