### ISSUE TITLE
Produce Anchor Sponsorship Audio 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#152]
The task was to create an audio recording for our sponsor Anchor.fm to monetize our audio on all our streaming platfrom.

**Comment by sanmiayotunde** [comment]
This issue has been resolved. We should close it.

Thanks,
*Sanmi Ayotunde Ajanaku*
Team Leader - DaBible Foundation
www.dabible.com
