### ISSUE TITLE
Children mission Outreach with Bro Emmanuel Gamaliel. 

### ISSUE THREAD

**Issue by benedictatommy** [DaBible-Foundation/DaBible-MainHub#155]
**Please describe the task or issue:**
Hello,  please I need you to create blog post on those pictures they took during children's outreach day at zikpak.

**Comment by sanmiayotunde** [comment]
Can you kindly provide us the pictures?

**Comment by sanmiayotunde** [comment]
@emmanlex Kindly attend to this issue, and kindly work with @olumese to release this content next week.

**Comment by benedictatommy** [comment]
Here are the pictures.
 WhatsApp Audio 2021-05-25 at 8.27.20 AM.mpeg
<https://drive.google.com/file/d/1eFdRPg1VX6XkLEJIHvnu9w1ER8Yotf6_/view?usp=drive_web>
 WhatsApp Image 2021-05-25 at 5.23.52 AM.jpeg
<https://drive.google.com/file/d/10XzCrbEKX0nR9dxwpInM-VI5QwkShikW/view?usp=drive_web>
 WhatsApp Image 2021-05-25 at 8.27.18 AM.jpeg
<https://drive.google.com/file/d/10Se5kXPwQgvpiGF1kmijdr-v_jOVnnAG/view?usp=drive_web>
 WhatsApp Image 2021-05-25 at 8.59.23 PM.jpeg
<https://drive.google.com/file/d/1pfl2sSdHco8oZ7z5SlhhT7uhOCmz0qlK/view?usp=drive_web>
 WhatsApp Image 2021-05-25 at 9.00.35 PM.jpeg
<https://drive.google.com/file/d/1GsHnEAc3TsHgj8gcrhc4RGia_biAnMdC/view?usp=drive_web>
 WhatsApp Image 2021-05-25 at 9.03.44 PM.jpeg
<https://drive.google.com/file/d/12o_EqRbbXa7BeGjNHF1llw6lEvswMWkn/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.32 PM (1).jpeg
<https://drive.google.com/file/d/1Uyh3YJDUJMsgDIKnfcOC_J43w3cJP1z2/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.32 PM.jpeg
<https://drive.google.com/file/d/1Iyfa6wgWoGjcb_PmacXpWlUoZCFR2-of/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.33 PM (1).jpeg
<https://drive.google.com/file/d/167jSaXTm51CisX7f4UofRECqR407cW2X/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.33 PM.jpeg
<https://drive.google.com/file/d/1Nf7-KrLCAkwEQPpkidTVFsjCmvhYxiwd/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.34 PM.jpeg
<https://drive.google.com/file/d/1GnV6hqtM4CNKgowIUY2HrVO_NqTBUsmF/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.36 PM.jpeg
<https://drive.google.com/file/d/1tRUQO8BVqoyrOgYpKua-WxRfrDTWN1GE/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.39 PM.jpeg
<https://drive.google.com/file/d/1a0MgqHu0txxtRqhnhLZfqunPQtMqXu1H/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.44 PM.jpeg
<https://drive.google.com/file/d/1tvXl1YvVNBhePheYHisguSVPUHPuXNDS/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.46 PM.jpeg
<https://drive.google.com/file/d/1OaAqEJhR-eymoM_uft8g29lqznXf0pSN/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.10.47 PM.jpeg
<https://drive.google.com/file/d/1TBHx3_tmMMg7L73_agMaxMnctoeeIYpz/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.00 PM.jpeg
<https://drive.google.com/file/d/1oWi0FOxfyJjBVLYBr2LfqzDhFQCvyrP0/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.01 PM.jpeg
<https://drive.google.com/file/d/1zBH5vy3kK9l8Vrr0y0pzGa87Dl1MtAQD/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.03 PM.jpeg
<https://drive.google.com/file/d/1kTvvhwD4HMgyQvalCfzwXs3d2KFkXwzo/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.06 PM.jpeg
<https://drive.google.com/file/d/1IIqWZ1YMEFxIZmc9q3Ul85f6LpgNquLh/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.07 PM (1).jpeg
<https://drive.google.com/file/d/1ArjDvik4qOlkuIxycLGPh1wIR70HmkLk/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.07 PM (2).jpeg
<https://drive.google.com/file/d/1_mgoVm4e-M0gw8IIySCTmtg8qFw7PTeU/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.07 PM.jpeg
<https://drive.google.com/file/d/1qW8R2na0_SrnLFipuqmkEHGBFy01SsqY/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.08 PM (1).jpeg
<https://drive.google.com/file/d/1PtxRS0KV3WywfAs0shKAedc68nRhE9af/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.08 PM.jpeg
<https://drive.google.com/file/d/1WiJ7Xju8WCrFFgNEPpnLyzEJWWiEpP90/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.09 PM.jpeg
<https://drive.google.com/file/d/14J0UJ88fcju02Oma7Uo9Y0xYXorSSxAD/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.10 PM.jpeg
<https://drive.google.com/file/d/1aInFl9XZYkBt3PSYh1zJYqftsfS5ff4W/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.11 PM (1).jpeg
<https://drive.google.com/file/d/1pFGjCaamxKDS6RnZlQE4ZGv9U-55K6a5/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.11 PM.jpeg
<https://drive.google.com/file/d/1TRpRIXSrfP_DWf1aJ746uqesChCvd1Gu/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 3.11.12 PM.jpeg
<https://drive.google.com/file/d/1uEuHQ9iA1brlump_jg-lXlvyBlhVxb7_/view?usp=drive_web>
 WhatsApp Image 2021-05-27 at 6.07.33 AM.jpeg
<https://drive.google.com/file/d/1TgahP3aExpiIvBoebws_yl2X9bvCQ9JS/view?usp=drive_web>
 WhatsApp Image 2021-05-28 at 4.43.45 AM.jpeg
<https://drive.google.com/file/d/1I54AOmZB9jpjus1Z8XFOOXQGFqtuYy22/view?usp=drive_web>
 WhatsApp Image 2021-05-28 at 4.43.46 AM.jpeg
<https://drive.google.com/file/d/1koT9bWeWtDD0sjhBMe2CLy2eD-RIsAKt/view?usp=drive_web>
 WhatsApp Video 2021-05-27 at 2.56.23 PM.mp4
<https://drive.google.com/file/d/1kUwJYAQrLQzwWaX_I-jn1-J1duNjHFjo/view?usp=drive_web>
 WhatsApp Video 2021-05-27 at 2.56.27 PM.mp4
<https://drive.google.com/file/d/1byo2pj1ukcnltnr_ZbR2EXKqTxdz7hcE/view?usp=drive_web>
 WhatsApp Video 2021-05-27 at 3.06.08 PM.mp4
<https://drive.google.com/file/d/13bokL3LYDH_LFcyNVGafGcb4OdefLs7x/view?usp=drive_web>
 WhatsApp Video 2021-05-27 at 3.06.40 PM.mp4
<https://drive.google.com/file/d/1TA2zFyXNeWYI1qW_S_4lDMelt217Y1m-/view?usp=drive_web>
 WhatsApp Video 2021-05-27 at 3.07.38 PM.mp4
<https://drive.google.com/file/d/1g2TMfmBgE8D29HEyZ_74m1sn1E9Prudc/view?usp=drive_web>
 WhatsApp Video 2021-05-27 at 3.14.07 PM.mp4
<https://drive.google.com/file/d/132wn8-P8Jp3Af2K-UFsA8M88M6JmX2dT/view?usp=drive_web>
 WhatsApp Video 2021-05-27 at 7.55.33 AM.mp4
<https://drive.google.com/file/d/1aHZ_X-4NXBeEAIor-TvG4du6jp7xOtRg/view?usp=drive_web>

**Comment by emmanlex** [comment]
An issue has been created to complete issue #166. The MVP1 is in the works presently

**Comment by sanmiayotunde** [comment]
This issue is now resolve and the content is now LIVE

https://dabible.com/missions/pictures-from-zikpak-children-outreach-by-emmanuel-gammaliel/
