### ISSUE TITLE
Someone needs to learn how to developer gitHub pages for developers.dabible.com

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#156]
**Please describe the task or issue:**
We can use GitHub pages to set up our developers.dabible.com documentations page.

**Comment by TimilehinO** [comment]
Hey, I noticed you did not assign this job to anyone.

**Comment by sanmiayotunde** [comment]
We were supposed to assign it to Fola, can we move this to ideas section?

**Comment by TimilehinO** [comment]
Oh okay no problem.
