### ISSUE TITLE
Make campaign for Solar Audio Bible

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#160]
We need to raise some funds to acquire our solar audio bible sample. @sanmiayotunde and @olasubomi-o would think on how to raise the remaining funds

**Comment by sanmiayotunde** [comment]
@TimilehinO Here is the wetransfer LINK for the videos that we need to remove the background noise. 

Thanks.

**Comment by olasubomi-o** [comment]
We decided to use email marketing to reach out to potential donors. Currently awaiting a review on the email template from @sanmiayotunde @emmanlex before the email is sent out

**Comment by olasubomi-o** [comment]
This week we would focus on digital promotion(E-mail) and next week we would go traditional by reaching out to our inner circle
