### ISSUE TITLE
Creation and design of the UI Interface, of the listen online to the yoruba bible, web page.

### ISSUE THREAD

**Issue by olumese** [DaBible-Foundation/DaBible-MainHub#162]
**Please describe the task or issue:**
So the goals of this pageis to create a very good looking and and user friendly page in which people can listen to our yoruba bible online.

**Additional information:**

**Comment by emmanlex** [comment]
Hey @olumese, how far are you with this issue?

**Comment by olumese** [comment]
[
[Da Bible FOundation yoruba bible page UI UX Design Templste.pdf](https://github.com/DaBible-Foundation/DaBible-MainHub/files/6593420/Da.Bible.FOundation.yoruba.bible.page.UI.UX.Design.Templste.pdf)
](url)

**Comment by olumese** [comment]
[Uploading Da Bible FOundation yoruba bible page UI UX Design Templste.pdf…]()

**Comment by olumese** [comment]
[Da Bible FOundation yoruba bible page UI UX Design Templste.pdf](https://github.com/DaBible-Foundation/DaBible-MainHub/files/6593473/Da.Bible.FOundation.yoruba.bible.page.UI.UX.Design.Templste.pdf)

**Comment by sanmiayotunde** [comment]
Great job Olumese!

Thanks,
*Sanmi Ayotunde Ajanaku*
Team Leader - DaBible Foundation
www.dabible.com

**Comment by olumese** [comment]
[Da.Bible.FOundation.yoruba.bible.page.UI.UX.Design.Templste 222.pdf](https://github.com/DaBible-Foundation/DaBible-MainHub/files/6593524/Da.Bible.FOundation.yoruba.bible.page.UI.UX.Design.Templste.222.pdf)
![ValidShortAfricanfisheagle-max-1mb](https://user-images.githubusercontent.com/84947607/120692464-a76e6f80-c45c-11eb-999b-9fca385eb397.gif)
 Second idea i just came up with

**Comment by sanmiayotunde** [comment]
Hahhaha lol, breaking your laptop is actualy also a good idea lol. The moment you move from heavy softwares like photoshop and corelDraw to simpler web applications such as figma, sketch and canva, your laptop will be relieved from the heavy processing task.

**Comment by sanmiayotunde** [comment]
The two PDF above are actually the same thing.
