### ISSUE TITLE
Content: Create new content on Leviticus Makpa for CNN Heroes entry

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#165]
We have to create new content for Leviticus Makpa for a CNN heroes submission. CNN honors people who have done exemplary work in helping humanity. These people are people passionate and zealous for the work they do. We believe Leviticus Makpa to be such a person and we want to share his story out there. 

- [x] Create MVP 1
- [ ] Create MVP 2

**Comment by emmanlex** [comment]
The article for MVP 1 has been created

**Comment by emmanlex** [comment]
@sanmiayotunde how far with getting a peer-review of this document?

**Comment by sanmiayotunde** [comment]
We are waiting for the video documentary that is being produced in Nigeria currently. The director is almost ready, and Bro Emmanuel Gammaliel will be paying her very soon so that we can have all the videos.

This video is what we are adding to the CNN Heroes content.

**Comment by olasubomi-o** [comment]
Awaiting review of the recently sent article to CNN hero
