### ISSUE TITLE
Google Ads: Create google ads for Leviticus/Benita Makpa blog post

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#175]
- Create google ads to promote the benita blog post
-  Create google ads to promote the Leviticus blog post
- Create google ads to promote the donation post for Benita
- Readjust the budget to be more aggressive towards this ad group
- This should run for 2 weeks then the budget would be readjusted

**Comment by TimilehinO** [comment]
Got it will do
