### ISSUE TITLE
Edit, Add Effects and Render the Audio Bible sound recorded by Victoria 

### ISSUE THREAD

**Issue by TimilehinO** [DaBible-Foundation/DaBible-MainHub#177]
**Please describe the task or issue:**
Victoria has recorded some books of the bible in her language, that we need to edit to sound official and ready for the consumers.

**Additional information:**

**Comment by olasubomi-o** [comment]
@olasubomi-o would be working with @TimilehinO on this issue

**Comment by TimilehinO** [comment]
Scheduling a meeting with Victoria today June/22/2021 time set to 2pm Central time
