### ISSUE TITLE
Documentation: DaBible Sprint Week Report

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#182]
Please fill out the [DaBible Sprint Plan Week 24](https://docs.google.com/spreadsheets/d/1ftt0jagVQvCvgfepI5Ouuob5UY9EL2epfn5dC7P3wfI/edit?pli=1#gid=1186140236). Include what went well, what to improve, and action items.

**Comment by TimilehinO** [comment]
Yes sir will do

**Comment by emmanlex** [comment]
The DaBible Sprint Plan week 24 was completed successfully. Thank you everyone
