### ISSUE TITLE
Write a Detailed Description for Hausa Audio Bible on Google Play

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#183]
We need to add a full description for our Hausa Audio Bible on Google Play, right now we are using the Yoruba's description.

**Comment by emmanlex** [comment]
This Hausa Audio Bible App is the FIRST of its kind. The only app with both the old testament and new testament bible made available in audio format. 

We are a group of young Christians using our technical skills to provide the Bible in our mother’s tongue. After the success of the Yoruba Audio Bible app and the Pidgin Bible App, we are expanding and are now releasing our Hausa audio bible.

This Hausa Audio Bible App is provided to you by the DaBible Foundation and dedicated to the late missionary, Leviticus Makpa.

As our fastest production ever, we spent six months transcribing, typing raw manuscripts, recording, and putting this bible app together. We are glad that we can make it available to you.

Our mission at DaBible Foundation is to put the Bible in digital format in every African home. We encourage you to donate to support us for the continuity of this project. We are vibrant youths empowered by God to give you a great online bible experience without compulsory internet.

FEATURES OF THE HAUSA AUDIO BIBLE APP
✔ No Internet required to READ Bible Text at all.
✔ No Internet required to LISTEN to audios AFTER you download.
✔ Delete unwanted downloaded chapters on your phone memory.
✔ Optimized download speed for the fastest user experience.
✔ Interactive storytelling, great audio quality, and correct pronunciation.
✔ Clear headings and subheadings.
✔ Switch between Hausa and English text without interruptions.
✔ Proper Hausa punctuation and correct audio pronunciation.
✔ Share Bible verses on Facebook, Twitter, Whatsapp, etc
✔ Easy to navigate Bible books and chapters
✔ Increase or reduce the font size to desired sight level
✔ Simple-One-Click option to download bible chapters

Send comments, suggestions, and feedback to support@dabible.com. For more information, visit www.dabible.com

**Comment by emmanlex** [comment]
The description is provided above please review @sanmiayotunde
