### ISSUE TITLE
Create the Featured Images required for the App Listing of Hausa Audio Bible

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#184]
- [x] **Feature graphic**
        This will help promote your app in different places on Google Play. In case of cropping, avoid placing text near the edges, and center key visuals
       1,024 px by 500 px

- [x] **Phone - Phone screenshots**
       Upload at least 2 phone or tablet screenshots
       Upload 2–8 phone screenshots
       16:9 or 9:16 aspect ratio
       Each side between 320 px and 3,840 px

- [x] **Tablet - 7-inch tablet screenshots** 
        Upload at least 2 phone or tablet screenshots
        Upload up to 8 7-inch tablet screenshots
       16:9 or 9:16 aspect ratio
       Each side between 320 px and 3,840 px

- [x] **10-inch tablet screenshots -  Upload at least 2 phone or tablet screenshots**
       Upload up to 8 10-inch tablet screenshots
       16:9 or 9:16 aspect ratio
       Each side between 320 px and 3,840 px

- [ ] Video - Record a Hausa video by for youtube

**Comment by olumese** [comment]
Request to add some light tweaks and changes to the pphone featured images design
