### ISSUE TITLE
Internal testing of the hausa audio bible

### ISSUE THREAD

**Issue by olumese** [DaBible-Foundation/DaBible-MainHub#185]
The goal is to test the app, find the vunerabilties on the app, find out if the app is crashing, when its crash why its crashing, please explain the test, the crash analytics. It may be time cosuimng but it must be done
![Screenshot_20210614-082410_WhatsApp](https://user-images.githubusercontent.com/84947607/121918339-d0a7bf00-ccea-11eb-9b54-679411bd3ee1.jpg)

**Comment by fagb3mi** [comment]
This task has been assigned to other team members as I use an iPhone and can't test the app.
