### ISSUE TITLE
Blog: Create a blog header Graphic for Hausa audio bible app release

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#190]
I require an image with screenshots and mockup of the Hausa Audio Bible for the feature image in the blog post I am about to release.

 @olumese 

- Please create a feature image of dimensions **1200 x 628 pixels** 
- Include at least three image of screenshots with android device mock ups. 
you can use this [blog](https://dabible.com/all-categories/pidgin-audio-bible-app-now-available-on-android-and-ios-devices/) for reference 

- [ ] Please include the screenshot.

**Comment by sanmiayotunde** [comment]
Hello @emmanlex,

Thanks for pushing for this.


Thanks,
*Sanmi Ayotunde Ajanaku*
Team Leader - DaBible Foundation
www.dabible.com

**Comment by olumese** [comment]
![huasa bible featured image](https://user-images.githubusercontent.com/84947607/122339214-a249ff80-cef5-11eb-985e-56e578086001.jpg)
