### ISSUE TITLE
Content: Create Hausa Android Release App Blog post

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#191]
Write a blog post that announces the release of the Hausa Bible App. 

- [x] Write Blog Post  @emmanlex 
- [x] Put Blog Post on website @emmanlex 
- [x] Review Blog post @olasubomi-o @sanmiayotunde 
- [x] Get @TimilehinO to create google ad
Link to Blog Post: [Hausa App Release Blog](https://dabible.com/hausa-audio-bible/hausa-audio-bible-android-app-launch/)

**Comment by emmanlex** [comment]
Blog post [MVP 1](https://docs.google.com/document/d/1durn6Fy0mmM2_QcCQa5ebiFlc0b2rB15QOCYXaEgsLM/edit?usp=sharing) has been written

**Comment by TimilehinO** [comment]
got it will do
