### ISSUE TITLE
Hausa Audio Bible App Release

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#192]
Release plan for Hausa Audio Bible - Emma

- [x] Release the blog post when the app goes live. - @emmanlex and @olumese 
- [x] Write an email template on Mautic that will be sent out. - @olasubomi-o @kehinde2134
- [x] Write a short push notification message that will be sent out. - @emmanlex 
- [x] Discuss with Evelyn for possibility of shooting a video - @emmanlex
- [x] Email people who subscribed to us about the release of Hausa Bible - @olasubomi-o @kehinde2134 
- [x] Contact Evelyn to plan a Hausa Release video that looks like this - @emmanlex

**Comment by sanmiayotunde** [comment]
App is now finally released
