### ISSUE TITLE
Bug in Hausa Audio Bible App that crashes with change to background settings.

### ISSUE THREAD

**Issue by aluko123** [DaBible-Foundation/DaBible-MainHub#193]
**Please describe the task or issue:**
An attempt to change the background music or volume of the app causes it to crash repeatedly. We would need to completely disable those options.

**Additional information:**

**Comment by aluko123** [comment]
Attached is a video of this bug triggering crashes: https://photos.google.com/photo/AF1QipNqJqUYgCnA4yOMMBcf2Sf2uulNMOc1LovGgJl7

**Comment by TimilehinO** [comment]
@aluko123 Hey any update on this issue.

**Comment by sanmiayotunde** [comment]
I have fixed the issue
