### ISSUE TITLE
Clean up youtube

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#197]
We have 4 different Youtube channels. @sanmiayotunde would be cleaning up our youtube channel and give us feedback on what each and every channel would do. 

We need to separate dabible from personal channels.

Migrate DaBible content that is on sanmi personal youtube to DaBible channels to make things more transparent

**Comment by TimilehinO** [comment]
Hey Subomi any updates on this?

**Comment by sanmiayotunde** [comment]
We have ressolved this issue
