### ISSUE TITLE
Update the Leviticus Mapka Blog Post with Relevant Information

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#198]
@emmanlex Please use the details below to update and iterate the Leviticus Makpa blog posts below.

- [x] https://dabible.com/all-categories/bro-leviticus-makpa-killed-by-bandits-as-a-missionary-in-niger-state/
- [x] https://dabible.com/missions/introducing-our-leviticus-makpas-missionary-field-in-niger-state/
- [x] Mention name of primary school (Ceto Academy)
- [x] Mention specific dates, mission field name, city, loccal goverrnment, 

**Additional information:**

THE EXIT OF A GENERAL MURDERED 21/05/2021
The remains of late Evangelist Leviticus Markus Makpa was laid to rest alongside his three year old son (Godsend) in Suleja, Niger state on Saturday 22nd May, 2021. Before his untimely death, late Evangelist Leviticus was a missionary who served with the Mission Field Evangelistic Outreach amongst the Kambari people in Tunga Maji, Rijau local government area of Niger state.

To the glory of God, he was responsible for the conversion of locals including fulanis in their numbers. While serving, he established the first and only primary school (Ceto Academy) in 2012 for the locals as he used it as a medium of evangelizing to them as he was doing his best to catch them young. He and his team built the school from scratch to finish with their bare hands. 

Late evang. Leviticus got married to his wife Benita on the 16th of December, 2017 and they both were blessed with a son and a daughter. They also adopted 7 kids from the tribes of Kambari, Dukawa and Fulani.

He was a graduate of Industrial Chemistry at the University of Jos. He abandoned his certificate to go and serve God and humanity. In a bid to do more, he proceeded to attend the Mission Minds Bible School. Before his demise, he was almost done with his master's degree program in the United States of America via correspondence.

This general was murdered On 21st May, 2021 with his son by armed men as they ran into a cave to hide from the bandits that had attacked them earlier. His offence was that he chose to serve the Lord and humanity.

His wife has a conviction to continue the work with time. Especially for the sake of their adopted kids and others given out for adoption as she is bent on them becoming all God has planned for them to become. 

Brother Levi, you fought a good fight, you where at your duty post. We celebrate your life on Earth but we miss you on this side of eternity.

Rest on my brother. We shall surely meet at the feet of our master.

Bobly Chibueze Asoronye
Mission Minds International, Jos
Plateau State, Nigeria.
+2348064329346 For Enquires

**Comment by emmanlex** [comment]
I edited and added the new information into the blogpost including [A missionary raising 126 children ](https://dabible.com/missions/a-missionary-in-nigeria-raising-126-children-under-thatched-roofs/)
