### ISSUE TITLE
Research: Ruth Chapter 3 audio quality

### ISSUE THREAD

**Issue by TimilehinO** [DaBible-Foundation/DaBible-MainHub#205]
**Please describe the task or issue:**
So after conducting my research. I've discovered the reason why Ruth chapter 3 came out with a sample rate of 16000. So, when I used my iPhone mic the sample rate was 48000 which is good and I tested Lossless and Compressed audio formats. They both came out nice, so Lossless audio is an audio file that keeps the data of the audio but is not noticeable to the ear, but the file size is increased by much. The compressed audio format just removes the audio data but is not noticeable though.  So moving forward I would recommend not to use AirPods to record since they do not have the ability to give out a sample rate of 48000. Also, the iPhone voice memo app defaults to compressed audio and I wouldn't recommend changing it.

**Additional information:**

**Comment by sanmiayotunde** [comment]
Wow thanks Timi, this is awesome!!!!!!!

**Comment by TimilehinO** [comment]
Yes sir.
