### ISSUE TITLE
Test and Improve SOLAR AUDIO BIBLE

### ISSUE THREAD

**Issue by olumese** [DaBible-Foundation/DaBible-MainHub#214]
**Please describe the task or issue:**

- [x] Inform Victoria that we need Vinyl cover, Rope, and Rubber Cover

- [ ] Have meeting with Ugo, Rob and Bolarinwa (for Data)

**Additional information:**

**Comment by TimilehinO** [comment]
Hey Olumese any updates on this?

**Comment by fagb3mi** [comment]
Bro. Sanmi and other members involved in this project would have to have a meeting with Ugo, Rob, and Bolarinwa (for Data).
We have completed task 1, as soon as task 2 is completed we would be closing the issue. 
@sanmiayotunde

**Comment by sanmiayotunde** [comment]
Thanks Iyin

Thanks,
*Sanmi Ayotunde Ajanaku*
Team Leader - DaBible Foundation
www.dabible.com
