### ISSUE TITLE
People who are not yet on Github

### ISSUE THREAD

**Issue by TimilehinO** [DaBible-Foundation/DaBible-MainHub#224]
**Please describe the task or issue:**
Please add these individuals to github as soon as possible.
- [x] Iyin Fagbemi
- [x] Kehinde Oyediran
- [x] Kenneth
- [x] Olumese

**Additional information:**
If you have any questions, please comment down below.

**Comment by sanmiayotunde** [comment]
@TimilehinO I have sent out invitation to both Kenneth and Kehinde
