### ISSUE TITLE
Creating Sub Repos or another private repo for unrelated dabible projects

### ISSUE THREAD

**Issue by TimilehinO** [DaBible-Foundation/DaBible-MainHub#229]
**Please describe the task or issue:**
Hey Sanmi, can you create short repos for LG, Pana, and Rccgna

**Additional information:**
If you have any questions, please feel free to ask and comment down below.

**Comment by sanmiayotunde** [comment]
This issue has now been resolved, we now have a private repo on DaBible called DaBible-Private-Projects. You can check it here
