### ISSUE TITLE
Review of work done by Timi on GitHub

### ISSUE THREAD

**Issue by TimilehinO** [DaBible-Foundation/DaBible-MainHub#231]
**Please describe the task or issue:**
Hey Emmanuel, can you go over the work and issues I've created to make sure I'm doing things right.

**Additional information:**
If you have any questions, please feel free to ask and comment down below.

**Comment by TimilehinO** [comment]
Thank you @sanmiayotunde for the renaming.

**Comment by emmanlex** [comment]
Comments on GitHub Management @TimilehinO 
- so we can use this project management software called ZenHub (the very good stuff)
- the title format for issues needs improvement too.
