### ISSUE TITLE
RCCGNA Seminary - Change Non-Degree Programs to Certificate Programs

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#234]
**Please describe the task or issue:**
@olumese  We have been requested to change the word Non-Degree to Certificate Programs

1. Menu Navigation
![image](https://user-images.githubusercontent.com/23180033/125354947-0790e500-e32a-11eb-8b3e-2c3290b294f3.png)
![image](https://user-images.githubusercontent.com/23180033/125355202-59396f80-e32a-11eb-8794-96090fba2c15.png)

2. URL: https://rccgnaseminary.org/admission/non-degree/
![image](https://user-images.githubusercontent.com/23180033/125354991-17102e00-e32a-11eb-8693-e59a5db983c0.png)

![image](https://user-images.githubusercontent.com/23180033/125355150-4aeb5380-e32a-11eb-8641-38f2a47b3c36.png)

3. URL: https://rccgnaseminary.org/admission/
![image](https://user-images.githubusercontent.com/23180033/125355081-2f804880-e32a-11eb-9da9-c9a2d70df678.png)

4. URL: https://rccgnaseminary.org/academics/non-degree-programs/
![image](https://user-images.githubusercontent.com/23180033/125355239-65bdc800-e32a-11eb-8fdf-62e3af42bd69.png)

5. URL: https://rccgnaseminary.org/academics/
![image](https://user-images.githubusercontent.com/23180033/125355326-7ff7a600-e32a-11eb-9698-3f5bf975ad89.png)

Please fix all these issues ASAP

**Comment by olumese** [comment]
![dfv](https://user-images.githubusercontent.com/84947607/125405475-a2121800-e36c-11eb-8c6f-0d9f7936d8d8.JPG)
![scv](https://user-images.githubusercontent.com/84947607/125405481-a3434500-e36c-11eb-9a5b-28b603aa9510.JPG)
![fvb](https://user-images.githubusercontent.com/84947607/125405482-a3434500-e36c-11eb-9200-478929c2623c.JPG)
