### ISSUE TITLE
RCCGNA - Add the Abuja and Adding Dr Ajiboye's Phone Number

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#236]
@olumese please add the address on this flyer here to the Porthacourt box

Then add Dr. Ajiboye's phone number as another WhatsApp contact that people can contact.

- [x] Add Abuja Address
- [x] Add Dr Ajiboye's Phone Number

![image](https://user-images.githubusercontent.com/23180033/125360966-432fad00-e332-11eb-8ce7-639c9a3b57d9.png)

URL: https://rccgnaseminary.org/meet-the-president-rccg-north-america-seminary-greenville-texas-usa/
![image](https://user-images.githubusercontent.com/23180033/125361064-678b8980-e332-11eb-9464-222a63c443cc.png)

**Comment by sanmiayotunde** [comment]
It's Abuja address not port Harcourt

**Comment by olumese** [comment]
It May be confusing to our users by add two phone numbers so we decided to use only one phone number each

**Comment by sanmiayotunde** [comment]
I agree with you Olumese
