### ISSUE TITLE
Order T-Shirt for Victoria

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#250]
**Please describe the task or issue:**
@olasubomi-o please help me order 5 different color T shirts for Victoria.

The shirts will be printed with the design below

https://www.canva.com/design/DAEkUIXQnkw/O9XtD00bt4IujhMLtkl-yw/edit

**Comment by olasubomi-o** [comment]
Ok sir, any colors in mind or I should pick

**Comment by sanmiayotunde** [comment]
@olasubomi-o What is the status for this issue?

**Comment by olasubomi-o** [comment]
There is minimum order of 12, I believe we spoke casual but I didn't get any sort of green light on what to do

**Comment by olumese** [comment]
![Welcome](https://user-images.githubusercontent.com/84947607/127241548-3d10465f-6522-4cdd-bba6-96ed691bb29a.png)

**Comment by olumese** [comment]
https://www.canva.com/design/DAElcKvB1IA/YkxWeSD-5yGAVHervKWReQ/edit

**Comment by olumese** [comment]
https://www.canva.com/design/DAElcKvB1IA/lgQ2BJQIOcditdiT6Jf2CA/view?utm_content=DAElcKvB1IA&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview

**Comment by olasubomi-o** [comment]
Orders placed. Probably an hour or two for price feedback and date

**Comment by sanmiayotunde** [comment]
Thanks @olasubomi-o What is the cost so that we can send it to you.

**Comment by sanmiayotunde** [comment]
You should be using DaBible Card for such transactions that are DaBible related for our accountability.

**Comment by olasubomi-o** [comment]
Ok sir, could you please send me the card details on private slack. I could
not pay yesterday because they said the min order of 12 is per design.
Hence, they are going to charge $20 extra for Victoria shirts and for ours
we would need to add 2 more shirts to avoid the $20. So yesterday I tried
emailing other screen printing companies but no response  so I guess we
might just have to go with them. Sorry for the late response, yesterday was
a bit hectic

**Comment by olasubomi-o** [comment]
P.S. I already ordered it cause we have been taken too long with the shirt
lol

**Comment by sanmiayotunde** [comment]
Thanks @olasubomi-o Let's go to the bank and get a card in your name since you will be doing much of the finances.

**Comment by TimilehinO** [comment]
Thank you, everyone.
