### ISSUE TITLE
The entire book of Exodus in Hausa Audio on Dreamhost is faulty

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#256]
**Please describe the task or issue:**
Please refer to the screenshotss below

**Additional information:**
![image](https://user-images.githubusercontent.com/23180033/127576196-13a99427-73bd-4b32-a7cf-4fe7bbb1792e.png)

**Comment by olasubomi-o** [comment]
<img width="1280" alt="Screen Shot 2021-07-30 at 9 46 54 AM" src="https://user-images.githubusercontent.com/67253470/127662501-c3239db4-ac2d-4b67-bf21-a8b018c342b3.png">

Resolved
