### ISSUE TITLE
Make a slide show on user awareness for our solar audio bible acquisition model

### ISSUE THREAD

**Issue by fagb3mi** [DaBible-Foundation/DaBible-MainHub#271]
Link to parent document - https://docs.google.com/presentation/d/1puT1wS76U4-Cii-W8Sl0M2HZWMv-kvbJw5FZIvgvUTk/edit#slide=id.gc6f919934_0_57

**Comment by olasubomi-o** [comment]
Hmm, what's user awareness about @sanmiayotunde @fagb3mi , did some googling and it's showing cybersecurity term

**Comment by sanmiayotunde** [comment]
hahahaha lol,

This is aboutt how do we get users

Thanks,
*Sanmi Ayotunde Ajanaku*
Team Leader - DaBible Foundation
www.dabible.com

**Comment by fagb3mi** [comment]
What he said ^

**Comment by olasubomi-o** [comment]
Done
