### ISSUE TITLE
Make a slide show on Donor acquisition model for our solar audio bible acquisition model

### ISSUE THREAD

**Issue by fagb3mi** [DaBible-Foundation/DaBible-MainHub#273]
Link to parent document - https://docs.google.com/presentation/d/1puT1wS76U4-Cii-W8Sl0M2HZWMv-kvbJw5FZIvgvUTk/edit#slide=id.gc6f919934_0_57

**Comment by olasubomi-o** [comment]
Similar to user acquisition because our target audience are donors
