### ISSUE TITLE
Get data for solar audio bible acquisition

### ISSUE THREAD

**Issue by fagb3mi** [DaBible-Foundation/DaBible-MainHub#283]
Get data on 30, 60, and 90-day overview on how users access content on the Yoruba audio bible app

**Comment by emmanlex** [comment]
I'm picking our comparatively higher user activity of the year. 
30 Days (June 1st - June 30th) 

image.png
image.png

60 Days (May 2nd - June 30th) 

image.png
image.png
90 Days (May 2nd - July 30th)

image.png
image.png

**Comment by emmanlex** [comment]
I have sent an email of the data to you as requested
