### ISSUE TITLE
Create a share button for blog post

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#32]
Create a share button on all our blog post for easy sharing.

**Comment by sanmiayotunde** [comment]
@olasubomi-o 

I have created the share button on all our blog posts. You can test the integration on the blog post below, and here is an screenshot.

https://dabible.com/blog/solar-audio-bible-for-the-elderly-project-kickstarted/

![image](https://user-images.githubusercontent.com/23180033/111831657-af872c00-88bd-11eb-80b4-106eff550d57.png)
