### ISSUE TITLE
Take a Google Adwords Grant for Non Profit & Ultimate Google Adwords Training class

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#36]
Take google ads class

https://lgelectronics.udemy.com/course/google-adwords-grant-for-nonprofits/

https://lgelectronics.udemy.com/course/the-ultimate-google-adwords-training-course/

**Comment by sanmiayotunde** [comment]
I think we have all taken this course, we can close this issue now.
