### ISSUE TITLE
Contact Levitcus Makpa 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#39]
@sanmiayotunde Please provide the contact information for Leviticus Makpa. Thank you sir

**Comment by sanmiayotunde** [comment]
@emmanlex Here is Mr Leviticus phone number +234 818 878 6541. He is available on WhatsApp. Please contact him.

**Comment by emmanlex** [comment]
Thanks @sanmiayotunde. I have made contact to Mr Leviticus on Whatsapp and we now working on finish the MVC3 blog post.
