### ISSUE TITLE
Write MVC 3 for the Missionary Quest Blog 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#40]
Write MVC 3 for the Missionary Quest Blog. presently the blog post for Leviticus Makpa as had unsatisfactory results. The new goal is to write a blog that has more page views and less bounce rates (reduce bounce rate to 60%). 

**Traffic from March 6th - 12th
Pageviews: 24
Unique page views: 12
Average Time on Page: 00:01:55
Bounce rate: 81.82%**

  | Current | Target
-- | -- | --
Pageviews | 24 | 200
Unique Page Views | 12 | 160
Bounce rate | 81.82% | 60%

**Comment by sanmiayotunde** [comment]
@emmanlex hope this task is going on smoothly

**Comment by emmanlex** [comment]
Wrote another blog post Levitucus Makpa. Creating MVC3 now seems redundant. You can check the link to it here. 
https://dabible.com/missions/a-missionary-in-nigeria-raising-126-children-under-thatched-roofs/
