### ISSUE TITLE
@emmanlex96 verify link up of slack and GitHub 

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#42]
There is a need to link up GitHub and slack so that when Issues are made on GitHub it updates on our slack channel

**Comment by emmanlex** [comment]
Slack and github link, having issues finishing up this project @sanmiayotunde

**Comment by emmanlex** [comment]
@olasubomi-o are you taking up this task?

**Comment by aluko123** [comment]
Done
