### ISSUE TITLE
Create an artwork for Easy worship

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#46]
Create an artwork for Easy worship

**Comment by emmanlex** [comment]
Artwork has been created for instagram size post and blog posting.
![Copy of Blog header - Made with PosterMyWall (3)](https://user-images.githubusercontent.com/50557337/111821737-fe7a9480-88b0-11eb-8563-13240dd36b2d.png)
![Copy of Blog header - Made with PosterMyWall (2)](https://user-images.githubusercontent.com/50557337/111821754-03d7df00-88b1-11eb-9503-e26151e09f71.png)

**Comment by sanmiayotunde** [comment]
Hello @emmanlex 

You put two logos on each other sir, this is confusing.

This should be the flow of the design.

Yoruba Audio Bible [logo]
now available on
Easy Worship [logo]

**Comment by sanmiayotunde** [comment]
@emmanlex where is the new designs?

**Comment by emmanlex** [comment]
I apologize I have  the new design below 
![Yorubapost2](https://user-images.githubusercontent.com/50557337/112188464-039d5380-8bd1-11eb-9441-eb0b14328b97.png)
![Yorubapost](https://user-images.githubusercontent.com/50557337/112188487-0730da80-8bd1-11eb-9001-4cad0ed147ff.png)
