### ISSUE TITLE
Testing out easyworship 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#47]
Test out easyworship using the credentials provided in the email.

**Comment by olasubomi-o** [comment]
How do we access easy worship. No credential or link was provided

**Comment by sanmiayotunde** [comment]
@olasubomi-o we will test this in church tonight.

**Comment by emmanlex** [comment]
I went over EasyWorship on Sunday to check out the Yoruba version on the software and took some screen shots for our blog use. 
![EASY_MOREAVAILABLES](https://user-images.githubusercontent.com/50557337/112186747-70afe980-8bcf-11eb-8d38-30d4e4229da1.PNG)
![EASY_PREVIEW](https://user-images.githubusercontent.com/50557337/112186750-70afe980-8bcf-11eb-9adb-e2e88ceef0b2.PNG)
![EASY_SCRIPTURE](https://user-images.githubusercontent.com/50557337/112186754-71488000-8bcf-11eb-8d5b-b403c3328088.PNG)
![EASY_YOR 1](https://user-images.githubusercontent.com/50557337/112186756-71e11680-8bcf-11eb-8ed8-f53b40739ee4.PNG)
![EASY_YOR 2](https://user-images.githubusercontent.com/50557337/112186757-71e11680-8bcf-11eb-947c-a55473059352.PNG)
![EASY_YOR 3](https://user-images.githubusercontent.com/50557337/112186758-71e11680-8bcf-11eb-9509-14612498d601.PNG)
![ESAY_YOR INSTALL](https://user-images.githubusercontent.com/50557337/112186759-7279ad00-8bcf-11eb-8594-d82122839568.PNG)

**Comment by emmanlex** [comment]
It worked pretty fine but advise we do more testing and also open a forum that people can post their difficulties to. 
**What I observed** 
- no serious lag was observed
- download and installing were pretty simple and easy to do
- the bible text loaded quite easily

**Comment by sanmiayotunde** [comment]
I have done good testing on the church computer.

Everything looks good for now. Thanks for the great job.
