### ISSUE TITLE
Working on Google strategy/ Launch google ads

### ISSUE THREAD

**Issue by olasubomi-o** [DaBible-Foundation/DaBible-MainHub#48]
@TimilehinO and I would discuss the google strategy we would use for this sprint week and implement those strategy

**Comment by emmanlex** [comment]
@TimilehinO what are we doing with this topic

**Comment by emmanlex** [comment]
@olasubomi-o What are we doing about this topic

**Comment by olasubomi-o** [comment]
We already created a strategy and we discussed it a while back. We made an even distribution of campaigns to head in order to reduce the work load and work faster. The strategy worked.
