### ISSUE TITLE
Create a google ad for our "Yoruba Bible is now available on EasyWorship" blog post.

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#51]
Hi guys,
Please create a google ad for our "Yoruba Bible is now available on EasyWorship" blog post. It was published 23 March 2021 and so far we have had very little data, a google ad will be great. Thank you.
Here is the link to the blog post
https://dabible.com/blog/yoruba-bible-is-now-available-on-easyworship/

**Comment by olasubomi-o** [comment]
Ad for support and awareness of the program has been completed. We would monitor the data in the next sprint round and make any change based on received data

**Comment by olasubomi-o** [comment]
<img width="1280" alt="Screen Shot 2021-04-03 at 10 43 44 AM" src="https://user-images.githubusercontent.com/67253470/113483518-788e4a00-9469-11eb-8e0e-5b8122eb14ec.png">
