### ISSUE TITLE
Fix the Recommendations and Optimization Score for Google Ads.

### ISSUE THREAD

**Issue by sanmiayotunde** [DaBible-Foundation/DaBible-MainHub#53]
- [x] Get more clicks on your responsive search ads by improving your headlines and descriptions 
- [x] Make your account easier to manage by removing redundant keywords 

![image](https://user-images.githubusercontent.com/23180033/112725732-ac0c2a00-8ee7-11eb-94e6-e146f91178b4.png)

**Comment by emmanlex** [comment]
I have optimized the Google Ads to 100%. I also remove redundant keywords

<img width="1277" alt="Screen Shot 2021-04-19 at 11 36 59 PM" src="https://user-images.githubusercontent.com/50557337/115338593-bd53f980-a168-11eb-9b39-23790ddddc1c.png">
<img width="244" alt="Screen Shot 2021-04-19 at 11 32 53 PM" src="https://user-images.githubusercontent.com/50557337/115338594-bdec9000-a168-11eb-9f2b-af11faddcdc5.png">
