### ISSUE TITLE
Upload AudioBible on Spotify using AnchorFM - MVC1 - Genesis

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#62]
Upload Yoruba and Pidgin AudioBible on to Spotify

- [x] Create an account on [Anchor](https://anchor.fm/)
- [x] Get all the assets such as images, logo, and text description of the podcast.
- [ ] Upload audio multiple files of Genesis Yoruba
- [ ] Upload audio multiple files of Genesis Pidgin
- [ ] Upload audio multiple files of Genesis Hausa

**Comment by olasubomi-o** [comment]
https://docs.google.com/presentation/d/1t_HZif2MwSYqd3ucDnSlzLniLX_u3q4qVujno8sRlUY/edit?usp=sharing

**Comment by olasubomi-o** [comment]
- Do research on how to publish bible verses as an album
- Separating podcast and album under one account
-

**Comment by sanmiayotunde** [comment]
@olasubomi-o 

What is the update on this project?

**Comment by olasubomi-o** [comment]
The following issues need to be resolved.

- Creation of CDBaby account, when I tried to add the account info I was unable to succeed. The login credential is the same as the Gmail login
- Anchor has been completed we just need to start publishing
- The cover art could be better, not sure if we have a vector type of this logo
<img width="1280" alt="Screen Shot 2021-04-06 at 5 07 15 PM" src="https://user-images.githubusercontent.com/67253470/113784551-3f6d0880-96fb-11eb-8921-d1d56b39219c.png">

**Comment by emmanlex** [comment]
We have resolved the cdbaby login issue @olasubomi-o. We also will work on the cover art for the album.

**Comment by emmanlex** [comment]
We talked to the cdbaby support team and found out all we need to do to get out content uploaded. The correspondence with the agent is linked below.
[Chat with cdbaby agent](https://docs.google.com/document/d/17evMsepy9WwTdEwbrQ7GG10sEZ8l6nZvMzErfRrAqv8/edit?usp=sharing)

**Comment by emmanlex** [comment]
We decide that we would use another platform to than CD BABY because of the price and commission on CDBaby.  It was not the best platform for what we decided to upload. For cd baby, we would have to pay $29 for each album and plus $20 UPC. A total of $49. Each album can contain only 50 files and we have 929 files. So not cost-effective. then I suggested ONErpm and distrokid, we chose ONErpm.
 
analysis | DistroKid | ONErpm
-- | -- | --
COMMISSION | 0% | 15%
DISTRIBUTION FEE | unlimited releases for… 1 artist = $19.99/yr 2 artists = $35.99/yr 5 artists = $79.99/yr 10 artists = $139.99/yr | $0
YEARLY FEE | unlimited releases for… 1 artist = $19.99/yr 2 artists = $35.99/yr 5 artists = $79.99/yr 10 artists = $139.99/yr | $0
YOUTUBE MONETIZATION | opt in | automatic
WITHHOLD TAXES FROM ARTISTS FROM FOREIGN COUNTRIES | yes | no
PANDORA RADIO SUBMISSION | yes | yes
SOUNDCLOUD MONETIZATION | no | yes
YOUTUBE UGC CONTENT ID MONETIZATION (commission) | $4.95 per single, and $14.95 for each release of 2+ songs, per year. | 30%, automatic
TAKEDOWN COST | free | free
CUSTOM LABEL NAME | with musician plus plan ($35.99/yr) | yes
SIGN UP FEE | $0 | $0
OPEN TO ALL? | yes | yes
# OF OUTLETS | 150+ | 100+
FEE FOR ADDING OUTLETS? | $0 manual or $7.95/release automated | $0
COST of UPC CODES? | free | free
COST of ISRC CODES? | free | free
  | HIDDENS FEE |

**Comment by emmanlex** [comment]
Sad news, ONErpm says they won't distribute our content. We had already uploaded our content and we even did a cover on ONErpm we were set for distribution but ONErpm shocked us by saying they don't distribute content like ours.

Chats: 

Izabella 1 day ago Hello ;) Thank you for contacting our support team! As previously reported, we don't distribute this kind of content. It fit in a podcast style and must be distributed directly by the store: https://podcasters.spotify.com/ Our approval team notified you through Ticket ID: 855585. In order to clarify your doubts, you can access our FAQ. (https://onerpm.com/support/faq). Have a great day!

**Comment by emmanlex** [comment]
WE need a new way to upload our videos

**Comment by emmanlex** [comment]
The upload of Audio files to Spotify through Anchor has begun. I started with Genesis and @olasubomi-o @TimilehinO will continue on with this project. A new issue #87 has been created to document this project.
