### ISSUE TITLE
Create a donations link for Leviticus Makpa 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#63]
The log is now live but we still need a link for people who want to donate towards supporting the missionary in question. Please create a donations link for Leviticus Makpa  @sanmiayotunde

**Comment by sanmiayotunde** [comment]
This issue has been resolved, we now have a donations link for Bro Leviticus Makpa's blog

![image](https://user-images.githubusercontent.com/23180033/113484850-1b49c700-9470-11eb-9fac-720cbf52397f.png)
