### ISSUE TITLE
Blog post for Easter

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#67]
This is our blog post for Easter 2021. We would like to more interaction with our users on DaBible.com. So, @sanmiayotunde please post this blog post on DaBible.com

https://docs.google.com/document/d/12vzC_BqDom-hwPnnMMctGLsQ3njZfiEjg0FBqk56n2w/edit

**Comment by sanmiayotunde** [comment]
Hello @emmanlex This issue has been resolved and the blog post is now published LIVE!

https://dabible.com/all-categories/2021-easter-message-we-rejoice/

Thanks
