### ISSUE TITLE
Addition of Leviticus Makpa audio to blog post

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#75]
We are creating an audio addition to our blog post for [Missionary Leviticus Makpa](https://dabible.com/missions/a-missionary-in-nigeria-raising-126-children-under-thatched-roofs/). I will be working with @TimilehinO  on this project. We want to create sort of a podcast feel on every such blog post. 
 

- [x] Send audio files to @TimilehinO. The **[Audio File](https://drive.google.com/drive/folders/1WpUiVp3pA7TXIEUbIeEYhOQYJrKzQz2D?usp=sharing)** 
- [x] Work with @TimilehinO to record my dialogue 
- [x] Make a recording ready for @sanmiayotunde to upload

**Comment by emmanlex** [comment]
I will send the audio files through google drive, go by tapping **[Drive](https://drive.google.com/drive/folders/1WpUiVp3pA7TXIEUbIeEYhOQYJrKzQz2D?usp=sharing)** @TimilehinO

**Comment by emmanlex** [comment]
The audio is ready and is available for @sanmiayotunde to upload

**Comment by TimilehinO** [comment]
I have made a pull request with the project file and audio file which is in MP3.

**Comment by emmanlex** [comment]
Another issue #75 was opened by @TimilehinO to finish up this project. The project was completed.
