### ISSUE TITLE
2000 user capacity on MailChimp

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#83]
We have to clear out our Mailchimp to prevent it from exceeding 2000 users. Reason: our free account can only support 2000 users. More info will be provided

**Comment by emmanlex** [comment]
It is a continous check

**Comment by sanmiayotunde** [comment]
1,777 contacts have then ARCHIVED in Mailchimp. The contacts can be restored in the future but they will not receive any email or marketing milestone in Mailchimp.

Now we can continue using Mailchimp to forward new contacts to Mautic
