### ISSUE TITLE
YouTube Shout Out - we are rocking it

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#84]
We had 45K minutes on April Whoop whoop. Also 50 new subscribers. We are rocking on YouTube

**Comment by emmanlex** [comment]
Please provide details @sanmiayotunde

**Comment by sanmiayotunde** [comment]
Hello,

Here is the report for the YouTube

**Reported Date:**  Apr 15, 2021

![image](https://user-images.githubusercontent.com/23180033/115938782-6482aa80-a461-11eb-9ab1-51646db34c64.png)



Thanks
