### ISSUE TITLE
Mother's Day Blog post 

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#88]
Write a blog post for the DaBible.com website for publication at 6 am CST. This is part of our steps to increase activity and interaction on our website. 

- [x]  Write a blog post for mother's day. The deadline is 11 pm
- [x] Review and Post blogpost @emmanlex @sanmiayotunde 
- [x] Create google ad for blog post @TimilehinO

**Comment by emmanlex** [comment]
I have finished the blog post just in the nick of time. Please review @sanmiayotunde @olasubomi-o 

(Mother's Day Blog Post)[https://docs.google.com/document/d/1QokIAlpgsF5ZU3WJM9ce4Ngm2MG1pRCv-7ANRImHI84/edit?usp=sharing]

**Comment by TimilehinO** [comment]
Ad made for Mother's Day Blog post
