### ISSUE TITLE
Presigned URL for Pidgin Audio Bible (android)

### ISSUE THREAD

**Issue by aluko123** [DaBible-Foundation/DaBible-MainHub#91]
Creating a presigned url so the android bible can play audio while restricting public access to wasabi. This creates a form of privacy in sending HTML requests from server to server.

**Comment by aluko123** [comment]
Update: the presigned URL has been received, but more work is needed to be done to tie both the connection stream, and the media player.

**Comment by aluko123** [comment]
Update: the media plays on next chapter now, but the previous media needs to stop working to continue.

**Comment by aluko123** [comment]
- [ ] Audio progress bar buggy on next chapter click
- [ ] Play/pause button not working
- [ ] Audio from previous chapter doesn't stop when you turn to next chapter

**Comment by emmanlex** [comment]
The presigned URL issue was confirmed resolved by @sanmiayotunde. Some new issues however have been created to resolve other bugs see issue #144
