### ISSUE TITLE
Issue with Bible upload on anchor

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#92]
![Screen Shot 2021-05-11 at 10 52 07 AM](https://user-images.githubusercontent.com/50557337/117847065-a4120a80-b247-11eb-806a-82b6e73fd7f9.png)
There is an issue with the album art you guys are using. Please update to the ones used previously.

**Comment by emmanlex** [comment]
it is easy, click the image and it takes you to a new tab. Download it from there

**Comment by TimilehinO** [comment]
We have fixed it
