### ISSUE TITLE
Changed Pidgin Bible Login Page

### ISSUE THREAD

**Issue by aluko123** [DaBible-Foundation/DaBible-MainHub#95]
Changed the login page of the pidgin Bible to be in line with the Yoruba Bible's. This makes it easy for consumers who aren't willing to use other forms of authentication, to still have access the wonderful content of the Bible. 

- [x] Added a skip button to the home page
- [x] Changed the logo to pidgin
- [x]  Added a login feature through user's social media account: facebook, email.

**Comment by sanmiayotunde** [comment]
Here is the link to our PIDGIN AUDIO BIBLE icon

https://drive.google.com/file/d/1O06C83y3l-h7mQVJlD8xlTopglSjqrAK/view?usp=sharing

**Comment by aluko123** [comment]
Revised the login page to update it to industry standard.
