### ISSUE TITLE
Create Blog Post for Leviticus Makpa exit to Glory

### ISSUE THREAD

**Issue by emmanlex** [DaBible-Foundation/DaBible-MainHub#98]
Leviticus Makpa, a missionary to the Kambari people in Niger State Northern Nigeria is dead. He and his son were shot dead on May 21st, 2021. May his soul rest in peace. @sanmiayotunde write a blog post for your brother in the lord, colleague, and fellow missionary.   

- [ ] Write and publish @sanmiayotunde 
- [ ] Edit post @emmanlex

**Comment by sanmiayotunde** [comment]
Content has been published online 

https://dabible.com/all-categories/bro-leviticus-makpa-killed-by-bandits-as-a-missionary-in-niger-state/

**Comment by emmanlex** [comment]
This issue was completed during the week 22 sprint.
